export const WORKOUTDONE_REQUEST = '@@workout/WORKOUTDONE_REQUEST'
export const WORKOUTDONE_SUCCESS = '@@workout/WORKOUTDONE_SUCCESS'
export const WORKOUTDONE_FAILURE = '@@workout/WORKOUTDONE_FAILURE'

export const WORKOUTDONEPOST_REQUEST = '@@workout/WORKOUTDONEPOST_REQUEST'
export const WORKOUTDONEPOST_SUCCESS = '@@workout/WORKOUTDONEPOST_SUCCESS'
export const WORKOUTDONEPOST_FAILURE = '@@workout/WORKOUTDONEPOST_FAILURE'


const ADD_WORKOUTDONE = 'DELETE_WORKOUTDONE'

const types = {
    WORKOUTDONE_REQUEST,
    WORKOUTDONE_SUCCESS,
    WORKOUTDONE_FAILURE,
    WORKOUTDONEPOST_REQUEST,
    WORKOUTDONEPOST_FAILURE,
    WORKOUTDONEPOST_SUCCESS,
    ADD_WORKOUTDONE
};

export default types;