version: '3'


services:
  mongo:
    image: 'mongo:latest'
  backend:
    build:
      dockerfile: Dockerfile
      context: ./ApiForTheApp
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_DATABASE-api
      - PORT=5000
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./App
    depends_on:
      - backend
  
  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./nginxConf
    ports:
      - "80:80"