export const EXERCISE_REQUEST = '@@exercise/EXERCISE_REQUEST'
export const EXERCISE_SUCCESS = '@@exercise/EXERCISE_SUCCESS'
export const EXERCISE_FAILURE = '@@exercise/EXERCISE_FAILURE'

export const EXERCISEDELETE_REQUEST = '@@workout/EXERCISEDELETE_REQUEST'
export const EXERCISEDELETE_SUCCESS = '@@workout/EXERCISEDELETE_SUCCESS'
export const EXERCISEDELETE_FAILURE = '@@workout/EXERCISEDELETE_FAILURE'

export const EXERCISEEDIT_REQUEST = '@@workout/EXERCISEEDIT_REQUEST'
export const EXERCISEEDIT_SUCCESS = '@@workout/EXERCISEEDIT_SUCCESS'
export const EXERCISEEDIT_FAILURE = '@@workout/EXERCISEEDIT_FAILURE'

const REMOVE_EXERCISE = 'DELETE_EXERCISE'
const EDIT_EXERCISE = 'EDIT_EXERCISE'

const types = {
    EXERCISE_REQUEST,
    EXERCISE_SUCCESS,
    EXERCISE_FAILURE,
    EXERCISEDELETE_REQUEST,
    EXERCISEDELETE_SUCCESS,
    EXERCISEDELETE_FAILURE,
    EXERCISEEDIT_REQUEST,
    EXERCISEEDIT_SUCCESS,
    EXERCISEEDIT_FAILURE,
    REMOVE_EXERCISE,
    EDIT_EXERCISE
};

export default types;