export const EXERCISE_REQUEST = '@@exercise/EXERCISE_REQUEST'
export const EXERCISE_SUCCESS = '@@exercise/EXERCISE_SUCCESS'
export const EXERCISE_FAILURE = '@@exercise/EXERCISE_FAILURE'

export const EXERCISEDELETE_REQUEST = '@@workout/EXERCISEDELETE_REQUEST'
export const EXERCISEDELETE_SUCCESS = '@@workout/EXERCISEDELETE_SUCCESS'
export const EXERCISEDELETE_FAILURE = '@@workout/EXERCISEDELETE_FAILURE'

const REMOVE_EXERCISE = 'DELETE_EXERCISE'

const types = {
    EXERCISE_REQUEST,
    EXERCISE_SUCCESS,
    EXERCISE_FAILURE,
    EXERCISEDELETE_REQUEST,
    EXERCISEDELETE_SUCCESS,
    EXERCISEDELETE_FAILURE,
    REMOVE_EXERCISE
};

export default types;