export const WORKOUT_REQUEST = '@@workout/WORKOUT_REQUEST'
export const WORKOUT_SUCCESS = '@@workout/WORKOUT_SUCCESS'
export const WORKOUT_FAILURE = '@@workout/WORKOUT_FAILURE'

export const WORKOUTPOST_REQUEST = '@@workout/WORKOUTPOST_REQUEST'
export const WORKOUTPOST_SUCCESS = '@@workout/WORKOUTPOST_SUCCESS'
export const WORKOUTPOST_FAILURE = '@@workout/WORKOUTPOST_FAILURE'

export const WORKOUTDELETE_REQUEST = '@@workout/WORKOUTDELETE_REQUEST'
export const WORKOUTDELETE_SUCCESS = '@@workout/WORKOUTDELETE_SUCCESS'
export const WORKOUTDELETE_FAILURE = '@@workout/WORKOUTDELETE_FAILURE'

export const WORKOUTEDIT_REQUEST = '@@workout/WORKOUTEDIT_REQUEST'
export const WORKOUTEDIT_SUCCESS = '@@workout/WORKOUTEDIT_SUCCESS'
export const WORKOUTEDIT_FAILURE = '@@workout/WORKOUTEDIT_FAILURE'

const REMOVE_WORKOUT = 'DELETE_WORKOUT'

const types = {
    WORKOUT_REQUEST,
    WORKOUT_SUCCESS,
    WORKOUT_FAILURE,
    WORKOUTPOST_REQUEST,
    WORKOUTPOST_FAILURE,
    WORKOUTPOST_SUCCESS,
    WORKOUTDELETE_REQUEST,
    WORKOUTDELETE_SUCCESS,
    WORKOUTDELETE_FAILURE,
    WORKOUTEDIT_REQUEST,
    WORKOUTEDIT_SUCCESS,
    WORKOUTEDIT_FAILURE,
    REMOVE_WORKOUT
};

export default types;